---
ID: "b541b720-fc13-45dd-aa9d-62a834618d1f"
Parent: "018d3494-c787-4474-8fed-7a786310346a"
Template: "018d3494-c787-4474-8fed-7a786310346a"
Path: /sitecore/templates/Feature/Sandbox Experience Accelerator/Composites/Rules Based Snippet Item/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200622T182012Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
